# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=750']
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --indent, '2']
      - id: check-shebang-scripts-are-executable
# - repo: local
#   hooks:
#   - id: format
#     name: Formatting
#     entry: npm run format
#     language: system
#     pass_filenames: false
#   - id: lint
#     name: Linting
#     entry: npm run lint
#     language: system
#     pass_filenames: false
